# Innersource Stale Issues and Pull Requests Workflow
name: Innersource Stale Issues and Pull Requests

# Trigger the workflow on a schedule and on workflow dispatch
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

# Define the job to call the stale action
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      # Call the stale action to close stale issues and PRs
      - name: Close Stale Issues and PRs
        uses: actions/stale@v9.1.0
      - name: Review
        run: echo "### Review :rocket:" >> $GITHUB_STEP_SUMMARY




